feat: add qa preview actions proto
Jitera-Product/jitera_proto pull request #101
Opened 2023-12-20 11:25 UTC by zrg-team

## Description

+ Add QA preview proto

## Issues

https://jitera.atlassian.net/browse/JAIS-368

# Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation to reflect the change
- [ ] I have updated the README.md to reflect the change
- [ ] I have added unit tests to prove that the update is effective and the feature works

2023-12-20 17:56 UTC, comictvn commented on protos/v2/project_source.proto
> +	string target_branch = 8;
what's target branch? @zrg-team . What's information of git you need?

2023-12-20 18:02 UTC, comictvn commented on protos/v2/project_preview.proto
> +message DeployGenerateScriptItem {
Do we need this at the moment?

2023-12-21 04:37 UTC, comictvn commented on protos/v2/project_source.proto
> +	string target_branch = 8;
I see target branch is pull request branch

2023-12-21 07:15 UTC, zrg-team commented on protos/v2/project_preview.proto
> +message DeployGenerateScriptItem {
yes i think. We need AI to generate script to deploy right ?

2023-12-21 07:16 UTC, zrg-team commented on protos/v2/project_source.proto
> +	string target_branch = 8;
I mean 
`branch`: user select branch
`jitera_branch`: base branch that use to push ERD
`target_branch `: branch that users want to do something with. Example feat/uc-1

2023-12-21 07:20 UTC, comictvn commented on protos/v2/project_preview.proto
> +message DeployGenerateScriptItem {
oh deployment script. yah I missed it

2023-12-21 07:20 UTC, comictvn approved these changes

2023-12-21 07:39 UTC, JoelNguyen1608 approved these changes

2023-12-21 07:47 UTC, jitera-carrick approved these changes

2023-12-21 07:53 UTC, jitera-carrick commented on protos/v2/project_source.proto
> +	string target_branch = 8;
@zrg-team We need an attribute: `uc_pr_name`. Ultron need it to create PR. @JoelNguyen1608

2023-12-24 10:20 UTC, comictvn requested changes
@zrg-team you might forgot require new project_preview file in this file ruby/lib/jitera_proto.rb

2023-12-24 10:25 UTC, comictvn commented on protos/v2/project_preview.proto
> +message ProjectPreviewDeployGenerateResponse {
we need docker base image like ruby:3.0.3-alpine3.15, node:18-alpine based on user import project.

2023-12-24 10:26 UTC, comictvn commented on protos/v2/project_preview.proto
> +  repeated DeployGenerateScriptItem previous_scripts = 5;
it will be blank at the first time?

2023-12-26 06:13 UTC, zrg-team commented on protos/v2/project_preview.proto
> +  repeated DeployGenerateScriptItem previous_scripts = 5;
yes

2023-12-26 06:52 UTC, comictvn commented on ruby/lib/payloads/v2/project_preview_pb.rb
> +require 'v2/project_source_pb'
we should remove it manually after codegen. I was faced issue yesterday

2023-12-26 07:05 UTC, zrg-team commented on ruby/lib/payloads/v2/project_preview_pb.rb
> +require 'v2/project_source_pb'
Hmm really. Just removed could you check again in your end

2024-01-08 08:00 UTC, merged