feat(TIT-172): add component specification proto
Jitera-Product/jitera_proto pull request #121
Opened 2024-04-16 08:10 UTC by akuita

## Description
- Add component specification message.
- Include component specification into figma response message.

## Issues
https://jitera.atlassian.net/browse/TIT-172

# Checklist

- [x] I have performed a self-review of my code

2024-04-16 11:40 UTC, AlexKlim approved these changes

2024-04-16 21:02 UTC, ak15 commented on protos/v2/project_figma.proto
> +  repeated ComponentSpecification component_specifications = 8;
`repeated` is not needed here @akuita 

Actually I tested with ruby after removing `repeated` I have so many changes  after protobuf generate in Ruby,  so I am confused should I push or not 


i tested locally after removing repeated it works , so request you to compile and push , for safer side because not sure so many changes in my local after protobuf generate will be ok and not cause any other issue

2024-04-16 21:03 UTC, ak15 requested changes
Minor help needed

2024-04-17 05:13 UTC, akuita commented on protos/v2/project_figma.proto
> +  repeated ComponentSpecification component_specifications = 8;
I might miss something, but why we don't need `repeated`, AIOpen should return a list of component specifications? 🤔

2024-04-17 05:17 UTC, ak15 commented on protos/v2/project_figma.proto
> +  repeated ComponentSpecification component_specifications = 8;
Sorry @akuita 

I pointed wrong line  😅 

https://github.com/Jitera-Product/jitera_proto/pull/121/files#diff-6439c3fb63d70012726e329e4b50badc50fee538796f1ef5f26312eddba090e5R8

2024-04-17 10:57 UTC, akuita commented on protos/v2/project_figma.proto
> +  repeated ComponentSpecification component_specifications = 8;
thanks, I have updated

2024-04-18 09:28 UTC, ak15 approved these changes

2024-04-18 09:29 UTC, merged